KRITA_DOCUMENT_IO_TYPE = "krita document"

KRITA_SAVE_IMAGE_NODE_TYPE = "KritaSaveImage"
KRITA_DOCUMENT_NODE_TYPE = "KritaDocument"

KRITA_INPUT_NODE_TYPES = []
KRITA_OUTPUT_NODE_TYPES = [KRITA_SAVE_IMAGE_NODE_TYPE]
